#syntax=docker/dockerfile:1

FROM python:latest
#install dependencies

RUN pip3 install python-telegram-bot --upgrade && pip3 install -r requierments.txt

#setup work enviorment
RUN mkdir app && cp . /app
WORKDIR /app
#create the directory for the vouchers
RUN mkdir Vouchers

#start the application
CMD ./app/10bisbot.py